name: Generate Stats Images

on:
  schedule:
    # تحديث تلقائي كل 12 ساعة
    - cron: "0 */12 * * *"
  workflow_dispatch: # لتشغيل السكربت يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Download GitHub Stats SVG
        # تحميل صورة الإحصائيات مع الثيم والإعدادات الخاصة بك
        run: curl -s "https://github-readme-stats.vercel.app/api?username=Ahmed-ALTURUK&theme=rose_pine&show_icons=true&include_all_commits=true&count_private=true" > dist/stats.svg

      - name: Download Top Languages SVG
        # تحميل صورة اللغات
        run: curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=Ahmed-ALTURUK&theme=rose_pine&layout=compact&langs_count=5" > dist/languages.svg

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
